server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java-projects
    username: postgres
    password: root-password-123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      user-deleted-topic-name: user-deleted-topic
    consumer:
      group-id: "admin-service-${random.uuid}"

logging:
  level:
    ru.blaskowitz.userserviceadmin.aspect: INFO